%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\pt19teje\Documents\Data\Mamip\Data\Mosaic\datasets\PS122_3_radiosonde_202005.tab
%
% Auto-generated by MATLAB on 14-Jan-2022 13:01:42

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = [159, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Citation", "MaturilliMarionHoldridgeDonnaJDahlkeSandroGraeserJrgenJaiserRal", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, [1, 2], "TrimNonNumeric", true);
opts = setvaropts(opts, [1, 2], "ThousandsSeparator", ",");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
PS1223radiosonde202005 = readtable("C:\Users\pt19teje\Documents\Data\Mamip\Data\Mosaic\datasets\PS122_3_radiosonde_202005.tab", opts);

%% Convert to output type
PS1223radiosonde202005 = table2array(PS1223radiosonde202005);

%% Clear temporary variables
clear opts