%%
function [ETIM hour minute sek press temp RHl lat lon altitude day month year PotTemp DewPoint] = readInRS2(filename_RS,i,station,ix)
%% Import data from text file
% Script for importing data from the following text file:
%
%filename_RS='C:\Users\pt19teje\Documents\Data\Mamip\Data\Mosaic\datasets\PS122_3_radiosonde_202005.tab'
%
% Auto-generated by MATLAB on 14-Jan-2022 13:26:10

%% Setup the Import Options
switch true
    case (strcmpi(station,'MOSAIC')==1)
        opts = delimitedTextImportOptions("NumVariables", 12);

        % Specify range and delimiter
        opts.DataLines = [2, Inf];
        opts.Delimiter = "\t";

        % Specify column names and types
        opts.VariableNames = ["Citation", "Time", "Lat", "lon", "Altitude", "Hgeom", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12"];
        opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];
        opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], "WhitespaceRule", "preserve");
        opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], "EmptyFieldRule", "auto");
        opts.ExtraColumnsRule = "ignore";
        opts.EmptyLineRule = "read";
        opts.MissingRule = 'omitrow';
        PS1223radiosonde1 = readtable(filename_RS, opts);
        
    case (strcmpi(station,'NYA')==1)
        opts = delimitedTextImportOptions("NumVariables", 11);

        % Specify range and delimiter
        opts.DataLines = [26, Inf]; %year 2017 26, 2018 27, 2019 27, 2020 28
        opts.Delimiter = "\t";

        % Specify column names and types
        opts.VariableNames = ["DateTime", "Latitude", "Longitude", "Altitudem", "hgeomm", "ETIMs", "PPPPhPa", "TTTC", "RH", "dddeg", "ffms"];
        opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
        opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
        opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");
        opts.ExtraColumnsRule = "ignore";
        opts.EmptyLineRule = "read";% Import the data
        
        PS1223radiosonde1 = readtable(filename_RS, opts);

        idx = ismissing(PS1223radiosonde1(:,{'Latitude','Longitude','ETIMs','Altitudem','TTTC','RH','PPPPhPa'}));
        PS1223radiosonde1{:,{'Latitude','Longitude','ETIMs','Altitudem','TTTC','RH','PPPPhPa'}}(idx) = -9999;
        
    case (strcmpi(station,'ACSE')==1)
        load(filename_RS)
        iRS = 1;
        PS1223radiosonde1 = [repmat(SondDataFL.mdayReal(iRS),1,length(SondDataFL.Height));...
            SondDataFL.Height'; SondDataFL.Pressure(iRS,:); SondDataFL.Temperature(iRS,:);...
            SondDataFL.RelHum(iRS,:);SondDataFL.WindSpeed(iRS,:);SondDataFL.WindDirection(iRS,:);...
            SondDataFL.SondeLat(iRS,:); SondDataFL.SondeLong(iRS,:)]';
        for iRS = 2 : length(ix)
            PS1223radiosonde = [repmat(SondDataFL.mdayReal(iRS),1,length(SondDataFL.Height));...
            SondDataFL.Height'; SondDataFL.Pressure(iRS,:); SondDataFL.Temperature(iRS,:);...
            SondDataFL.RelHum(iRS,:);SondDataFL.WindSpeed(iRS,:);SondDataFL.WindDirection(iRS,:);...
            SondDataFL.SondeLat(iRS,:); SondDataFL.SondeLong(iRS,:)]';
        PS1223radiosonde1 = [PS1223radiosonde1;PS1223radiosonde];
        end

end

%% Clear temporary variables
switch true
    case (strcmpi(station,'MOSAIC')==1)
    RSdata = table2array(PS1223radiosonde1);
    time = char(RSdata(:,2));
    case (strcmpi(station,'NYA')==1)
    RSdata = table2array(PS1223radiosonde1);
    time = char(RSdata(:,1));
    case (strcmpi(station,'Utq')==1)
    RSdata = table2array(PS1223radiosonde1);
    time = char(RSdata(:,11:29));
    case (strcmpi(station,'ACSE')==1)
    RSdata = PS1223radiosonde1;
    time = char(datestr(RSdata(:,1),31));
end
year = str2num(time(:,1:4));
month = str2num(time(:,6:7));
day = str2num(time(:,9:10));
hour = str2num(time(:,12:13));
minute = str2num(time(:,15:16));
sec = str2num(time(:,18:19));
%%
clear opts
time = time;
year = year;
day = day;
month = month;
hour = hour;
minute = minute;
sek = sec;
switch true
    case (strcmpi(station,'MOSAIC')==1)
        lat=str2num(char(RSdata(:,3)));
        lon=str2num(char(RSdata(:,4)));
        ETIM = str2num(char(RSdata(:,7)));
        altitude=str2num(char(RSdata(:,5)));
        %press=str2num(char(RSdata(:,8)));
        press = str2double(RSdata(:,8));
        temp=str2num(char(RSdata(:,9)))+273.15;
        PotTemp=temp.*(press/1000).^(-287/1004.6);
        RHl=str2num(char(RSdata(:,10)));
        WindSpeed=str2num(char(RSdata(:,12)));
        WindDirection=str2num(char(RSdata(:,11)));
    case (strcmpi(station,'ACSE')==1)
        lat=RSdata(:,8);
        lon=RSdata(:,9);
        ETIM = RSdata(:,1);
        altitude=RSdata(:,2);
        %press=str2num(char(RSdata(:,8)));
        press = RSdata(:,3);
        temp=RSdata(:,4);
        PotTemp=temp.*(press/1000).^(-287/1004.6);
        RHl=RSdata(:,5);
        WindSpeed=RSdata(:,8);
        WindDirection=RSdata(:,9);
     case (strcmpi(station,'NYA')==1)
        lat=str2num(char(RSdata(:,2)));
        lat(lat == -9999)=[];
        lon=str2num(char(RSdata(:,3)));
        lon(lon == -9999)= [];
        ETIM = str2num(char(RSdata(:,6)));
        ETIM(ETIM == -9999) = [];
        altitude=str2num(char(RSdata(:,4)));
        altitude(altitude == -999) = [];
        %press=str2num(char(RSdata(:,8)));
        press = str2double(RSdata(:,7));
        press(press == -9999) = 0;
        temp=str2num(char(RSdata(:,8)))+273.15;
        temp(temp == -9999) = [];
        PotTemp=temp.*(press/1000).^(-287/1004.6);
        RHl=str2num(char(RSdata(:,9)));
        RHl(RHl == -9999) = 0;
        %WindSpeed=str2num(char(RSdata(:,11)));
        %WindDirection=str2num(char(RSdata(:,10)));
     case (strcmpi(station,'Utq')==1)
        lat=str2num(char(RSdata(:,11)));
        lat(lat == -9999)=[];
        lon=str2num(char(RSdata(:,12)));
        lon(lon == -9999)= [];
        ETIM = str2num(char(RSdata(:,14)));
        ETIM(ETIM == -9999) = [];
        altitude=str2num(char(RSdata(:,13)));
        altitude(altitude == -999) = [];
        %press=str2num(char(RSdata(:,8)));
        press = str2double(RSdata(:,3))*10;
        press(press == -9999) = 0;
        temp=str2num(char(RSdata(:,1)))+273.15;
        temp(temp == -9999) = [];
        PotTemp=str2double(RSdata(:,9));
        PotTemp(PotTemp == -9999) = [];
        RHl=str2num(char(RSdata(:,2)));
        RHl(RHl == -9999) = 0;
        %WindSpeed=str2num(char(RSdata(:,11)));
        %WindDirection=str2num(char(RSdata(:,10)));
end
es_w=10.^(23.5470-4.9283*log10(temp)-...
    2937.4.*temp.^(-1));
qs_w=1000*.622*es_w.*(press-es_w).^(-1);
es_i=10.^(10.550-2667.*temp.^(-1));
ix=find(temp>273.15);es_i(ix)=es_w(ix);
qs_i=1000*.622*es_i.*(press-es_i).^(-1);
MixingRatio=RHl.*qs_w/100;
RHlI=100*MixingRatio./qs_i;
%PotTempE=thebol(press,...
%    temp,MixingRatio/1000);

temp = temp-273;
DewPoint=temp - ((100-RHl)/5);
end