%%
function [ETIM hour minute sek press temp RHl lat lon altitude day month year PotTemp DewPoint] = readInRS2(filename_RS, i, station, Myfileinfo)
%% Import data from text file
% Script for importing data from the following text file:
%
%filename_RS='C:\Users\pt19teje\Documents\Data\Mamip\Data\Mosaic\datasets\PS122_3_radiosonde_202005.tab'
%
% Auto-generated by MATLAB on 14-Jan-2022 13:26:10

%% Setup the Import Options
switch true
    case (strcmpi(station,'MOSAIC')==1)
        opts = delimitedTextImportOptions("NumVariables", 12);

        % Specify range and delimiter
        opts.DataLines = [2, Inf];
        opts.Delimiter = "\t";

        % Specify column names and types
        opts.VariableNames = ["Citation", "Time", "Lat", "lon", "Altitude", "Hgeom", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12"];
        opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];
        opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], "WhitespaceRule", "preserve");
        opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], "EmptyFieldRule", "auto");
        opts.ExtraColumnsRule = "ignore";
        opts.EmptyLineRule = "read";
        opts.MissingRule = 'omitrow';
        PS1223radiosonde1 = readtable(filename_RS, opts);
        
    case (strcmpi(station,'NYA')==1)
        opts = delimitedTextImportOptions("NumVariables", 11);

        % Specify range and delimiter
        opts.DataLines = [28, Inf]; %year 2017 26, 2018 27, 2019 27, 2020 28
        opts.Delimiter = "\t";

        % Specify column names and types
        opts.VariableNames = ["DateTime", "Latitude", "Longitude", "Altitudem", "hgeomm", "ETIMs", "PPPPhPa", "TTTC", "RH", "dddeg", "ffms"];
        opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
        opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
        opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");
        opts.ExtraColumnsRule = "ignore";
        opts.EmptyLineRule = "read";% Import the data
        
        PS1223radiosonde1 = readtable(filename_RS, opts);

        idx = ismissing(PS1223radiosonde1(:,{'Latitude','Longitude','ETIMs','Altitudem','TTTC','RH','PPPPhPa'}));
        PS1223radiosonde1{:,{'Latitude','Longitude','ETIMs','Altitudem','TTTC','RH','PPPPhPa'}}(idx) = -9999;
        
    case (strcmpi(station,'Utq')==1)
        filename_RS = strcat(Myfileinfo(1).folder,'/', Myfileinfo(1).name);
            ncid = netcdf.open(filename_RS,'NC_NOWRITE');
            [~,nvars,natts,unlimdimID] = netcdf.inq(ncid);
                    for i = 0 : nvars-1
                        varname = netcdf.inqVar(ncid,i);
                        test.(varname) = netcdf.getVar(ncid,i);
                        data = netcdf.getVar(ncid,i);
                        test.(varname) = data(:,:);
                        clear data varname
                    end
                    time1 = datevec(datetime(test.base_time, 'ConvertFrom', 'posixtime', 'Format', 'yyyy-MM-dd HH:mm:ss'));
                    timeUtq = [repmat(datenum(time1(1),time1(2),time1(3),5,30,0),333,1);...
                        repmat(datenum(time1(1),time1(2),time1(3),11,0,0),333,1);...
                        repmat(datenum(time1(1),time1(2),time1(3),17,30,0),333,1);...
                        repmat(datenum(time1(1),time1(2),time1(3),23,0,0),333,1)];
                    test = rmfield(test,{'base_time','time_offset','precip','qc_precip','qc_temp','source_temp',...
                    'qc_rh', 'source_rh','vap_pres','qc_vap_pres','qc_bar_pres','source_bar_pres',...
                    'qc_wspd','qc_wdir','qc_u_wind','source_u_wind','qc_v_wind','source_v_wind','qc_dp','source_dp',...
                    'qc_potential_temp','qc_sh','alt','rh_scaled', 'qc_rh_scaled','aqc_rh_scaled','vapor_source'});
                    % Create a new structure to store the modified data
                    newStruct = test;
                    % Define the number of rows to add (in this case, 1 row of zeros)
                    numRowsToAdd = 1;
                    % Iterate through each field of the structure
                    fieldNames = fieldnames(test);
                    for ifield = 1:numel(fieldNames)
                        % Get the data from the current field
                        currentData = test.(fieldNames{ifield});
                        % Determine the new size of the data
                        newSize = [size(currentData, 1) + numRowsToAdd, size(currentData, 2)];
                        % Create a new matrix with the desired size and fill it with zeros
                        newData = zeros(newSize);
                        % Copy the existing data into the new matrix, leaving the top rows as zeros
                        newData(numRowsToAdd+1:end, :) = currentData;
                        % Assign the new data to the field in the new structure
                        newStruct.(fieldNames{ifield}) = newData;
                    end
                    variableNames = fieldnames(newStruct);  
                    for iv = 3 : numel(variableNames)-2
                        fieldName = variableNames{iv};
                        RSutq.(fieldName) = [newStruct.(fieldName)(:,313); newStruct.(fieldName)(:,690);...
                            newStruct.(fieldName)(:,1050);newStruct.(fieldName)(:,1410)];
                    end   
                    RSutq.lat = repmat(test.lat,1332,1);
                    RSutq.lon = repmat(test.lon,1332,1);
                    RSutq.height = repmat(newStruct.height,4,1);
                    clear i natts ndims ncid nvars unlimdimID test time1 variablesNames
        for iRS = 2: length(Myfileinfo)
            filename_RS = strcat(Myfileinfo(iRS).folder,'/', Myfileinfo(iRS).name);
            ncid = netcdf.open(filename_RS,'NC_NOWRITE');
            [~,nvars,natts,unlimdimID] = netcdf.inq(ncid);
                    for i = 0 : nvars-1
                    varname = netcdf.inqVar(ncid,i);
                    test.(varname) = netcdf.getVar(ncid,i);
                    data = netcdf.getVar(ncid,i);
                    test.(varname) = data(:,:);
                    clear data varname
                    end
                    time2 = datevec(datetime(test.base_time, 'ConvertFrom', 'posixtime', 'Format', 'yyyy-MM-dd HH:mm:ss'));
                    timeUtq1 = [repmat(datenum(time2(1),time2(2),time2(3),5,30,0),333,1);...
                        repmat(datenum(time2(1),time2(2),time2(3),11,0,0),333,1);...
                        repmat(datenum(time2(1),time2(2),time2(3),17,30,0),333,1);...
                        repmat(datenum(time2(1),time2(2),time2(3),23,0,0),333,1)];
                    timeUtq = [timeUtq; timeUtq1];
                    test = rmfield(test,{'base_time','time_offset','precip','qc_precip','qc_temp','source_temp',...
                    'qc_rh', 'source_rh','vap_pres','qc_vap_pres','qc_bar_pres','source_bar_pres',...
                    'qc_wspd','qc_wdir','qc_u_wind','source_u_wind','qc_v_wind','source_v_wind','qc_dp','source_dp',...
                    'qc_potential_temp','qc_sh','alt','rh_scaled', 'qc_rh_scaled','aqc_rh_scaled','vapor_source'});
                    % Create a new structure to store the modified data
                    newStruct = test;
                    % Define the number of rows to add (in this case, 1 row of zeros)
                    numRowsToAdd = 1;
                    % Iterate through each field of the structure
                    fieldNames = fieldnames(test);
                    for ifield = 1:numel(fieldNames)
                        % Get the data from the current field
                        currentData = test.(fieldNames{ifield});
                        %currentData(currentData == -9999) = NaN;
                        % Determine the new size of the data
                        newSize = [size(currentData, 1) + numRowsToAdd, size(currentData, 2)];
                        % Create a new matrix with the desired size and fill it with zeros
                        newData = zeros(newSize);
                        % Copy the existing data into the new matrix, leaving the top rows as zeros
                        newData(numRowsToAdd+1:end, :) = currentData;
                        % Assign the new data to the field in the new structure
                        newStruct.(fieldNames{ifield}) = newData;
                    end
                    variableNames = fieldnames(newStruct);  
                    for iv = 3 : numel(variableNames)-2
                        fieldName = variableNames{iv};
                        RSutq1.(fieldName) = [newStruct.(fieldName)(:,313); newStruct.(fieldName)(:,690);...
                            newStruct.(fieldName)(:,1050);newStruct.(fieldName)(:,1410)];
                    end  
                    combinedStruct = RSutq;
                    RSutq1.lat = repmat(test.lat,1332,1);
                    RSutq1.lon = repmat(test.lon,1332,1);
                    RSutq1.height = repmat(newStruct.height,4,1);
                    % Get the fieldnames from one of the structures (assuming they have the same fieldnames)
                    fieldNames = fieldnames(RSutq);

                    % Iterate through each field
                    for i = 1:numel(fieldNames)
                        % Get the data from each structure
                        data1 = RSutq.(fieldNames{i});
                        data2 = RSutq1.(fieldNames{i});
                        combinedStruct.(fieldNames{i}) = [data1;data2];
                    end
                    RSutq = combinedStruct;
                    
                clear i natts ndims ncid nvars unlimdimID combinedStruct fieldNames RSutq1 RSutq1...
                    newData newSize test variableNames currentData data1 data2 newStruct fieldName...
                    numRowsToAdd time1 time2 Utq1 timestruct timeUtq1
        end  
        clear ifield iRS filename_RS iv Myfileinfo 
        RSutq.time = datestr(timeUtq,31);
        PS1223radiosonde1 = struct2table(RSutq);  
        %clear RSutq timeUtq
end

%% Convert to output type
year = str2num(RSutq.time(:,1:4));
month = str2num(RSutq.time(:,6:7));
day = str2num(RSutq.time(:,9:10));
hour = str2num(RSutq.time(:,12:13));
minute = str2num(RSutq.time(:,15:16));
sec = str2num(RSutq.time(:,18:19));
%%
clear opts
year = year;
day = day;
month = month;
hour = hour;
minute = minute;
sek = sec;

    lat = RSutq.lat;
    lat(lat == -9999)=[];
    lon = RSutq.lon;
    lon(lon == -9999)= [];
    ETIM = RSutq.height;
    ETIM(ETIM == -9999) = [];
    altitude=RSutq.height*1000;
    altitude(altitude == -999) = [];
    %press=str2num(char(RSdata(:,8)));
    press = RSutq.bar_pres*10;
    press(press == -9999) = 0;
    temp=RSutq.temp+273.15;
    temp(temp == -9999) = [];
    PotTemp=RSutq.potential_temp;
    PotTemp(PotTemp == -9999) = [];
    RHl=RSutq.rh;
    RHl(RHl == -9999) = 0;
    %WindSpeed=str2num(char(RSdata(:,11)));
    %WindDirection=str2num(char(RSdata(:,10)));

es_w=10.^(23.5470-4.9283*log10(temp)-...
    2937.4.*temp.^(-1));
qs_w=1000*.622*es_w.*(press-es_w).^(-1);
es_i=10.^(10.550-2667.*temp.^(-1));
ix=find(temp>273.15);es_i(ix)=es_w(ix);
qs_i=1000*.622*es_i.*(press-es_i).^(-1);
MixingRatio=RHl.*qs_w/100;
RHlI=100*MixingRatio./qs_i;
%PotTempE=thebol(press,...
%    temp,MixingRatio/1000);

temp = temp-273;
DewPoint=temp - ((100-RHl)/5);
end